version: "3.9"
services:
  db:
    container_name: internationalization-db
    image: interlinkproject/postgres:latest
    volumes:
      - idb-data:${PGDATA}
    env_file:
      - .env
    environment:
      - POSTGRES_MULTIPLE_DATABASES=weblate
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  weblate:
    image: weblate/weblate
    tmpfs:
    - /app/cache
    volumes:
    - weblate-data:/app/data
    restart: always
    depends_on:
    - db
    - weblate-cache
    environment:
      WEBLATE_SITE_DOMAIN: ${DOMAIN}
      WEBLATE_EMAIL_HOST: ${SMTP_SERVER}
      WEBLATE_EMAIL_HOST_USER: ${SMTP_USERNAME}
      WEBLATE_EMAIL_HOST_PASSWORD: ${SMTP_PASSWORD}
      WEBLATE_EMAIL_PORT: 587
      WEBLATE_DEBUG: 1
      WEBLATE_LOGLEVEL: DEBUG
      WEBLATE_SITE_TITLE: Weblate
      WEBLATE_ADMIN_NAME: Weblate Admin
      WEBLATE_ADMIN_EMAIL: ${FROM_EMAIL}
      WEBLATE_ADMIN_PASSWORD: admin
      WEBLATE_SERVER_EMAIL: ${FROM_EMAIL}
      WEBLATE_DEFAULT_FROM_EMAIL: ${FROM_EMAIL}
      WEBLATE_ALLOWED_HOSTS: "*"
      WEBLATE_REGISTRATION_OPEN: 1
      WEBLATE_URL_PREFIX: /weblate
      REDIS_HOST: weblate-cache
      REDIS_PORT: 6379
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: weblate
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.internationalization-weblate.rule=Host(`${DOMAIN}`)  && PathPrefix(`/weblate`)
      - traefik.http.routers.internationalization-weblate.service=internationalization-weblate
      - traefik.http.services.internationalization-weblate.loadbalancer.server.port=8080
      - traefik.http.routers.internationalization-weblate.entrypoints=websecure
      - traefik.http.routers.internationalization-weblate.tls.certresolver=letsencrypt
      - traefik.http.routers.internationalization-weblate.tls=true
    networks:
      - default
      - traefik-public
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  weblate-cache:
    image: redis:6-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - weblate-cache-data:/data
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  
networks:
  traefik-public:
    external: true
  default:
    name: internationalization-default

volumes:
  idb-data:
  weblate-data:
  weblate-cache-data:
