name: update-dev-environment
on:
  repository_dispatch:
    types: [update-dev-environment]
  push:
    branches:
      - "master"
    paths:
      - envs/base/**
      - envs/development/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /datadrive/data/interlink-project
            git pull --ff-only
            cd envs
            docker-compose -f base/docker-compose.yml -f development/docker-compose.dev.yml --env-file development/.env pull
            docker-compose -f base/docker-compose.yml -f development/docker-compose.dev.yml --env-file development/.env up -d
            docker-compose -f base/docker-compose.yml -f development/docker-compose.dev.yml exec catalogue python /app/app/pre_start.py
            docker-compose -f base/docker-compose.yml -f development/docker-compose.dev.yml exec coproduction python /app/app/pre_start.py
	          docker-compose -f base/docker-compose.yml -f development/docker-compose.dev.yml exec catalogue python /app/app/initial_data.py
	          docker-compose -f base/docker-compose.yml -f development/docker-compose.dev.yml exec coproduction python /app/app/initial_data.py